-- MySQL Script generated by MySQL Workbench
-- Mon Jul  2 09:53:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum` DEFAULT CHARACTER SET utf8 ;
USE `forum` ;

-- -----------------------------------------------------
-- Table `forum`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`categorie` ;

CREATE TABLE IF NOT EXISTS `forum`.`categorie` (
  `categorie_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`categorie_id`),
  UNIQUE INDEX `categorie_id_UNIQUE` (`categorie_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`message` ;

CREATE TABLE IF NOT EXISTS `forum`.`message` (
  `message_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contenu` BLOB NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `categorie_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `sujet_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `destinataire_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`message_id`),
  UNIQUE INDEX `message_id_UNIQUE` (`message_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`role` ;

CREATE TABLE IF NOT EXISTS `forum`.`role` (
  `role_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`sujet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`sujet` ;

CREATE TABLE IF NOT EXISTS `forum`.`sujet` (
  `sujet_id` INT(100) UNSIGNED NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(255) NULL DEFAULT NULL,
  `categorie_id` INT NULL,
  PRIMARY KEY (`sujet_id`),
  UNIQUE INDEX `sujet_id_UNIQUE` (`sujet_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forum`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`user` ;

CREATE TABLE IF NOT EXISTS `forum`.`user` (
  `user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(255) NULL DEFAULT NULL,
  `nom` VARCHAR(255) NULL DEFAULT NULL,
  `mail` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` VARCHAR(45) NULL DEFAULT NULL,
  `motdepasse` BLOB NULL DEFAULT NULL,
  `naissance` DATE NULL DEFAULT NULL,
  `inscription` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `pseudo`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC),
  UNIQUE INDEX `id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
